### ISSUE TITLE
[1.14.4] Mod conflict with camera mod missing gui.

### ISSUE THREAD

**Issue by ProsperCraft** [simibubi/TheMightyArchitect#7]
https://youtu.be/ksHPwdChXFs
One of my players found this and made a video for us.

If the camera mod is in the pack the bottom middle gui is missing, this explains why so many players were getting stuck in the architect mode :)

	[1.14.4] Camera Mod 1.4.3
	mightyarchitect-mc1.14.4_v0.4.5.jar

**Comment by ProsperCraft** [comment]
Crossposted here - https://www.curseforge.com/minecraft/mc-mods/camera-mod/issues/9

**Comment by simibubi** [comment]
Nice, well done discovering that!
Were there any messages in the logs? 
Camera mod has its intellectual property protected, troubleshooting might get a little tricky here.

What's interesting is that the Menu works, until the blueprint shader kicks in.

**Comment by ProsperCraft** [comment]
Here is his code- https://github.com/henkelmax/camera/

**Comment by simibubi** [comment]
Thank you, this will help immensely.
A few things are to notice right away - the mods use similar techniques and therefore essentially override each others behavior.
- The callback for scrolling is only granted to the mod loaded last. This is due to the workarounds we had to set up until forge ports the proper `ScrollEvent`. Relevant lines:
  * [Camera](https://github.com/henkelmax/camera/blob/4ef13096b765ec3c1688ac399c2f93bed775c397/src/main/java/de/maxhenkel/camera/ClientEvents.java#L62)
  * [TMA](https://github.com/simibubi/TheMightyArchitect/blob/aa56ad28dac53d07116e60782de61696f95ff8e7/src/main/java/com/simibubi/mightyarchitect/ScrollFixer.java#L27)
- The active shader used in the game gets set by both mods simultaneously. TMA and Camera will constantly fight over it. Further testing showed that both TMA and Camera break vanilla's use for the shader system (Spectating an Entity). Relevant Lines:
  * [Camera](https://github.com/henkelmax/camera/blob/1975e9f019e612a8a40c2b77d94d6d9a5d433f9b/src/main/java/de/maxhenkel/camera/ClientEvents.java#L86)
  * [TMA](https://github.com/simibubi/TheMightyArchitect/blob/aa56ad28dac53d07116e60782de61696f95ff8e7/src/main/java/com/simibubi/mightyarchitect/control/helpful/ShaderManager.java#L20)

As for the problems this issue was referring to initially, I haven't yet found a specific cause. 
TMA messing with the active shader could possibly cause Camera to cancel `RenderGameOverlayEvent`, which then causes the menu to disappear until the shader is inactive again.

I'm sure henkelmax has a better understanding, would be interesting to hear their thoughts on this.
Cheers!~

**Comment by henkelmax** [comment]
I think the best solution for the scroll issue would be a pull request for forge.
I already did create a scroll event, but never made a PR.
Somehow I lost the code but it shouldn't be that hard to do this again.

For the shader issue I have to look into it a little more.

**Comment by henkelmax** [comment]
So I surrounded the resetting of the shader with an if to prevent it being fired everytime:

https://github.com/henkelmax/camera/blob/2ecf39ebcc3ba4f8f7b199fc0fec4c0995e56d2d/src/main/java/de/maxhenkel/camera/ClientEvents.java#L209-L212

This should fix my mod fighting over TMAs setting of the shader...

**Comment by simibubi** [comment]
Most of this should be Resolved in 0.4.6
- No more Shader fighting from TMA's side.
- The Menus are now rendered in the overlay phase that Camera skips when running its rendering logic.
- For Scrolling we'll have to wait a bit longer. I saw a promising PR waiting for about a week now.  

Thanks again for the help, and feel free to re-open.
